version: 2.1
orbs:
  architect: giantswarm/architect@0.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push k8s-initiator-app chart"
          app_catalog: "giantswarm-incubator-catalog"
          app_catalog_test: "giantswarm-incubator-test-catalog"
          chart: "k8s-initiator-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/