version: 2.1
orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          name: push-k8s-initiator-to-quay
          image: "quay.io/giantswarm/k8s-initiator"
          context: architect
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - hold-push-k8s-initiator-to-aliyun-pr:
          type: approval
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker:
          name: push-k8s-initiator-to-aliyun-pr
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/k8s-initiator"
          context: architect
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-k8s-initiator-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker:
          name: push-k8s-initiator-to-aliyun-master
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/k8s-initiator"
          context: architect
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-app-catalog:
          name: "package and push k8s-initiator-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          context: architect
          chart: "k8s-initiator-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
