version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - hold-push-k8s-initiator-to-aliyun-pr
          filters:
            tags:
              only: /^v.*/

          image: giantswarm/k8s-initiator
      - hold-push-k8s-initiator-to-aliyun-pr:
          type: approval
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-app-catalog:
          name: "package and push k8s-initiator-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          context: architect
          chart: "k8s-initiator-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
