# This will set the OIDC settings of a cluster
  
command:
  - sh
  - -c
  - |
    APIMANIFEST=/manifests/k8s-api-server.yaml
    ISSUERURL=https://test.com
    CLIENTID=123123
    USERNAME_CLAIM=email
    GROUPS_CLAIM=groups
    if ! grep -q oidc-client-id $APIMANIFEST; then
      echo "OIDC Settings not present, applying"
      echo "Previous API yaml"
      cat $APIMANIFEST
      awk "/feature-gates/ { print; print \"    - --oidc-issuer-url=$ISSUERURL\n    - --oidc-client-id=$CLIENTID\n    - --oidc-username-claim=$USERNAME_CLAIM\n    - --oidc-groups-claim=$GROUPS_CLAIM\" ; next }1" $APIMANIFEST > /tmp/tmp_api.yaml
      mv /tmp/tmp_api.yaml $APIMANIFEST
      echo "New api yaml:"
      cat $APIMANIFEST
    else
      echo "OIDC Settings present"
      echo "Replacing the OIDC Settings"

      cp $APIMANIFEST /tmp/tmp_api.yaml
      sed -i -r -e "s,    - --oidc-issuer-url=(.+),    - --oidc-issuer-url=$ISSUERURL," /tmp/tmp_api.yaml
      sed -i -r -e "s,    - --oidc-client-id=(.+),    - --oidc-client-id=$CLIENTID," /tmp/tmp_api.yaml
      sed -i -r -e "s,    - --oidc-username-claim=(.+),    - --oidc-username-claim=$USERNAME_CLAIM," /tmp/tmp_api.yaml
      sed -i -r -e "s,    - --oidc-groups-claim=(.+),    - --oidc-groups-claim=$GROUPS_CLAIM," /tmp/tmp_api.yaml

      mv /tmp/tmp_api.yaml $APIMANIFEST
      echo "New api yaml:"
      cat $APIMANIFEST
    fi

initiators:
  - bash
