apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initiator.fullname" . }}
data:
  resources.yaml: |
{{- range $key, $file := .Values.files }}
    ---
{{ $file | indent 4 }}
{{- end }}
{{- if .Values.patches }}
{{- $patchResources := list }}
{{- range .Values.patches }}
{{- $jsonPatch := toJson .patch }}
{{- $ns := .namespace | default "default" }}
{{- $cmdOptions := printf "%s -n %s -p '%s'" .resource $ns $jsonPatch }}
{{- $patchResources = append $patchResources $cmdOptions }}
{{- end }}
  k8s-patches.sh: |-
    #!/bin/bash
{{- range $patchResources }}
    kubectl patch {{ . }}
{{- end }}
{{- end }}
