apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "initiator.fullname" . }}
  labels:
    app: {{ template "initiator.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "initiator.fullname" . }}
  template:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ template "initiator.fullname" . }}
      labels:
        app: {{ template "initiator.fullname" . }}
      annotations:
        releasetime: {{ now | quote }}
    spec:
      priorityClassName: {{ .Values.priority_class }}
{{ include "initiator.nodeSelector" . | indent 6 }}
      serviceAccountName: {{ template "initiator.fullname" . }}
      containers:
      - name: pause
        image: gcr.io/google_containers/pause-amd64:3.0
{{ toYaml .Values.resources | indent 10 }}
      initContainers:
{{ if has "bash" .Values.initiators }}
      - name: bash-initiator
        image: quay.io/giantswarm/k8s-initiator:{{ .Chart.Version }}
        command:
{{ toYaml .Values.command | indent 10 }}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: manifests-volume
          mountPath: /manifests
{{- include "initiator.extraVolumeMounts" . | indent 8 -}}
{{ end }}
{{ if has "k8s" .Values.initiators }}
      - name: k8s-initiator
        image: quay.io/giantswarm/k8s-initiator:{{ .Chart.Version }}
        volumeMounts:
        - name: config
          mountPath: /etc/k8s-initiator
{{- include "initiator.extraVolumeMounts" . | indent 8 -}}
{{ end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "initiator.fullname" . }}
      - name: manifests-volume
        hostPath:
          path: /etc/kubernetes/manifests
{{- include "initiator.extraVolumes" . | indent 6 }}
