{{- if .Values.kyvernoPolicyExceptions.enabled }}
  {{- if .Capabilities.APIVersions.Has "policy.giantswarm.io/v1alpha1/PolicyException" -}}
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: {{ template "initiator.fullname" . }}
  namespace: policy-exceptions
spec:
  policies:
  - disallow-capabilities-strict
  - disallow-privilege-escalation
  - disallow-host-namespaces
  - disallow-host-path
  - restrict-seccomp-strict
  - require-run-as-non-root-user
  - require-run-as-nonroot
  - restrict-volume-types
  targets:
  - kind: DaemonSet
    names:
    - {{ template "initiator.fullname" . }}*
    namespaces:
    - {{ $.Release.Namespace }}
  {{- end -}}
{{- end -}}