apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "initiator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "initiator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "initiator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "initiator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "initiator.fullname" . }}
rules:
{{- range $rule := .Values.rbac.rules }}
- apiGroups:
  {{- if $rule.apiGroup  }}
  - {{ $rule.apiGroup }}
  {{- else }}
  - ""
  {{- end }}
  resources:
  - {{ $rule.resource }}
  verbs:
  {{- range $verb := $rule.verbs }}
  - {{ $verb }}
  {{- end }}
{{- end }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - update
  - patch
  - get
  - list
