apiVersion: v1
appVersion: "v0.9.0"
home: https://github.com/giantswarm/k8s-initiator-app
description: The k8s initiator runs in a master node and applies some configuration when the master is new.
engine: gotpl
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
name: k8s-initiator-app
sources:
- https://github.com/giantswarm/k8s-initiator-app
- https://github.com/giantswarm/k8s-initiator-app/blob/master/README.md
version: [[ .Version ]]
