files:
- |
  ---
command:
  - sh
  - -c
  - |
    echo "No command set"

# container resources
resources: {}

# Make room to run the pod
priority_class: system-node-critical

psp:
  privileged: false
masterOnly: true
nodeSelector: {}
initiators:
  - bash
  - k8s
extraHostPaths: []
