files:
- |
  ---
command:
  - sh
  - -c
  - |
    echo "No command set"

image:
  registry: quay.io
  k8sInitiatorContainerImage:
    name: giantswarm/k8s-initiator
    tag: [[ .Version ]]
  pauseContainerImage:
    name: giantswarm/pause-amd64
    tag: 3.3

# container resources
resources: {}

# Make room to run the pod
priorityClassName: system-node-critical

psp:
  privileged: false
masterOnly: true
hostNetwork: true
nodeSelector: {}
affinity: {}
tolerations: {}
initiators:
  - bash
  - k8s
extraHostPaths: []
