affinity: {}

command:
  - sh
  - -c
  - |
    echo "No command set"

extraHostPaths: []

hostNetwork: true
hostPID: false
hostIPC: false

image:
  registry: gsoci.azurecr.io
  k8sInitiatorContainerImage:
    name: giantswarm/k8s-initiator
    tag: 0.10.0
  pauseContainerImage:
    name: giantswarm/pause-amd64
    tag: 3.3

kyvernoPolicyExceptions:
  enabled: true

global:
  podSecurityStandards:
    enforced: false

initiators:
  - bash
  - k8s

files:
- |
  ---

masterOnly: true

nodeSelector: {}

# Make room to run the pod
priorityClassName: system-node-critical

privileged: false

psp:
  privileged: false
  ipc: false
  pid: false

rbac:
  rules:
  - apiGroup:
    - ""
    resource:
    - nodes
    verbs:
    - update
    - patch
    - get
    - list

# container resources
resources: {}

tolerations: []
